vzstats.spec: fix %triggerin call
The problem is trigger -p is called with some arguments, which
we don't understand, leading to the following error:

	Non-fatal <unknown> scriptlet failure in rpm package
	vzstats-0.3.1-1.noarch
	ERROR: Unknown option /var/tmp/rpm-tmp.gxKwVQ
	Usage:
	....

So let's stop using -p for %triggerin

Signed-off-by: Kir Kolyshkin <kir@openvz.org>